pub mod no01_create_a_hashmap_with_new_function;
pub mod no02_remove_method;
pub mod no03_hashmaps_and_ownership;
pub mod no04_access_a_value_by_key;
pub mod no05_overwriting_a_value_with_an_existing_key;
pub mod no06_entry_method;
pub mod no07_hashset;
pub mod no08_hashset_operations;
pub mod project;
